# Generated by Django 4.2.4 on 2023-08-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_phone_number_otpcode_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
