# Generated by Django 4.2.4 on 2023-09-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpBanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_function', models.CharField(max_length=30)),
                ('blocked_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='otpcode',
            name='created2',
            field=models.DateTimeField(null=True),
        ),
    ]
