# Generated by Django 4.2.4 on 2023-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otpbanstatus_ban_statuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpbanstatus',
            name='error_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
