# Generated by Django 4.2.4 on 2023-09-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_otpbanstatus_error_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_list', models.CharField(blank=True, default='[]', max_length=100, null=True)),
            ],
        ),
    ]
