# Generated by Django 4.2.4 on 2023-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_errorlist_error_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlist',
            name='error_list',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
