# Generated by Django 4.2.5 on 2023-09-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_errorlist_error_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpbanstatus',
            name='error_list',
        ),
    ]
