# Generated by Django 4.2.5 on 2023-09-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_otpbanstatus_error_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlist',
            name='error_list',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
